<?php

use App\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        User::insert([
            ['name' => 'Klinik Mitra Kita', 'username' => 'Mitra Kita', 'password' => Hash::make('mitrakita'), 'kode' => '', 'role' => 'rs', 'faskes' => 'Klinik Mitra Kita'],
            ['name' => 'RSBANYUMANIK', 'username' => 'RSBANYUMANIK', 'password' => Hash::make('RSBANYUMANIK'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RSBANYUMANIK'],
            ['name' => 'RS BHAYANGKARA AKPOL', 'username' => 'RS AKPOL', 'password' => Hash::make('RS AKPOL'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS BHAYANGKARA AKPOL'],
            ['name' => 'RS BHAYANGKARA POLDA', 'username' => 'POLDA', 'password' => Hash::make('POLDA'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS BHAYANGKARA POLDA'],
            ['name' => 'RS COLUMBIA', 'username' => 'olive', 'password' => Hash::make('olivecolumbia'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS COLUMBIA'],
            ['name' => 'RINA', 'username' => 'RINA', 'password' => Hash::make('LUCKYKU'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS ELISABETH'],
            ['name' => 'RS GUNUNGSAWO', 'username' => 'indahrm', 'password' => Hash::make('bigboge'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS GUNUNG SAWO'],
            ['name' => 'umi', 'username' => 'umi', 'password' => Hash::make('umihermina'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS HERMINA PANDANARAN'],
            ['name' => 'RS Hermina Banyumanik', 'username' => 'hermina banyumanik', 'password' => Hash::make('hermina banyumanik'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS Hermina Banyumanik'],
            ['name' => 'RSISA', 'username' => 'RSISA', 'password' => Hash::make('RSISA'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS Islam Sultan Agung'],
            ['name' => 'kariadi', 'username' => 'kariadi', 'password' => Hash::make('kariadi'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS Kariadi'],
            ['name' => 'rspwdc', 'username' => 'rspwdc', 'password' => Hash::make('pedhet'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS Panti Wilasa Dr Cipto'],
            ['name' => 'rspwc', 'username' => 'rspwc', 'password' => Hash::make('rspwc'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS Pantiwiloso Citarum'],
            ['name' => 'rspm', 'username' => 'rspm', 'password' => Hash::make('rspm'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS Permata Medika'],
            ['name' => 'asihono', 'username' => 'roemani', 'password' => Hash::make('rm2016'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS ROEMANI'],
            ['name' => 'HANDAYANI', 'username' => 'HANDAYANI', 'password' => Hash::make('HANDAYANI'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS TELOGOREJO'],
            ['name' => 'tugurejo', 'username' => 'tugurejo', 'password' => Hash::make('tugurejo'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS Tugurejo'],
            ['name' => 'RS WILLIAM BOOTH', 'username' => 'RSWB', 'password' => Hash::make('RSWB'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS WILLIAM BOOTH'],
            ['name' => 'RSJD dr AMINO GONDOHUTOMO', 'username' => 'amino', 'password' => Hash::make('rsj'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RSJD dr AMINO GONDOHUTOMO'],
            ['name' => 'RST', 'username' => 'RST', 'password' => Hash::make('RST'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RST'],
            ['name' => 'anggie', 'username' => 'anggie', 'password' => Hash::make('ketileng'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RSUD K.R.M.T Wongsonegoro'],
            ['name' => 'RSU Ungaran', 'username' => 'RSU Ungaran', 'password' => Hash::make('RSU Ungaran'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RSUD Ungaran'],
            ['name' => 'RSPN UNDIP', 'username' => 'RSPN UNDIP', 'password' => Hash::make('RSPNSEMARANG'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RSN DIPONEGORO'],
            ['name' => 'RS LUAR SEMARANG', 'username' => 'RSLK', 'password' => Hash::make('RSLK'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS LUAR SEMARANG'],
            ['name' => 'RSIA KUSUMA PRAJA', 'username' => 'KUSUMAPRAJA', 'password' => Hash::make('KUSUMAPRAJA'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RSIA KUSUMA PRAJA'],
            ['name' => 'RSIA ANANDA', 'username' => 'ananda', 'password' => Hash::make('ananda'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RSIA Ananda'],
            ['name' => 'RSIA BUNDA', 'username' => 'bunda', 'password' => Hash::make('bunda'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RSIA BUNDA'],
            ['name' => 'RS SILOAM', 'username' => 'siloam', 'password' => Hash::make('siloam'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RS SILOAM'],
            ['name' => 'Klinik Grahasifa', 'username' => 'grahasifa', 'password' => Hash::make('grahasifa'), 'kode' => '', 'role' => 'rs', 'faskes' => 'Klinik Grahasifa'],
            ['name' => 'RSIA ANUGERAH', 'username' => 'anugerah', 'password' => Hash::make('anugerah'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RSIA ANUGERAH'],
            ['name' => 'RM Halmahera', 'username' => 'rmhalmahera', 'password' => Hash::make('rmhalmahera'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RM Halmahera'],
            ['name' => 'RM Karangdoro', 'username' => 'rmkarangdoro', 'password' => Hash::make('rmkarangdoro'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RM Karangdoro'],
            ['name' => 'RM Karangmalang', 'username' => 'rmkarangmalang', 'password' => Hash::make('rmkarangmalang'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RM karangmalang'],
            ['name' => 'RM Bangetayu', 'username' => 'rmbangetayu', 'password' => Hash::make('rmbangetayu'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RM Bangetayu'],
            ['name' => 'Klinik Esensia', 'username' => 'esensia', 'password' => Hash::make('esensia'), 'kode' => '', 'role' => 'rs', 'faskes' => 'Klinik Esensia'],
            ['name' => 'RM Ngalian', 'username' => 'rmngalian', 'password' => Hash::make('rmngalian'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RM Ngalian'],
            ['name' => 'Klinik Elisabeth', 'username' => 'klinikelisabeth', 'password' => Hash::make('klinikelisabeth'), 'kode' => '', 'role' => 'rs', 'faskes' => 'Klinik Elisabeth'],
            ['name' => 'RM Gunungpati', 'username' => 'rmgunungpati', 'password' => Hash::make('rmgunungpati'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RM Gunungpati'],
            ['name' => 'Klinik Namira', 'username' => 'kliniknamira', 'password' => Hash::make('kliniknamira'), 'kode' => '', 'role' => 'rs', 'faskes' => 'Klinik Namira'],
            ['name' => 'RM Tlogosari kulon', 'username' => 'rmtlogosarikulon', 'password' => Hash::make('rmtlogosarikulon'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RM Tlogosari kulon'],
            ['name' => 'rsiaplamonganindah', 'username' => 'rsiaplamonganindah', 'password' => Hash::make('rsiaplamonganindah'), 'kode' => '', 'role' => 'rs', 'faskes' => 'rsiaplamonganindah'],
            ['name' => 'rsbanyumanik2', 'username' => 'rsbanyumanik2', 'password' => Hash::make('rsbanyumanik2'), 'kode' => '', 'role' => 'rs', 'faskes' => 'rsbanyumanik2'],
            ['name' => 'RSPRIMAYA', 'username' => 'RSPRIMAYA', 'password' => Hash::make('RSPRIMAYA'), 'kode' => '', 'role' => 'rs', 'faskes' => 'RSPRIMAYA'],
            ['name' => 'Pusk Poncol', 'username' => 'poncol', 'password' => Hash::make('poncol'), 'kode' => 'P01', 'role' => 'puskesmas', 'faskes' => 'Pusk Poncol'],
            ['name' => 'Pusk Miroto', 'username' => 'miroto', 'password' => Hash::make('miroto'), 'kode' => 'P02', 'role' => 'puskesmas', 'faskes' => 'Pusk Miroto'],
            ['name' => 'Pusk Bandarharjo', 'username' => 'bandarharjo', 'password' => Hash::make('bandarharjo'), 'kode' => 'P03', 'role' => 'puskesmas', 'faskes' => 'Pusk Bandarharjo'],
            ['name' => 'Pusk Bulu Lor', 'username' => 'bululor', 'password' => Hash::make('bululor'), 'kode' => 'P04', 'role' => 'puskesmas', 'faskes' => 'Pusk Bulu Lor'],
            ['name' => 'Pusk Halmahera', 'username' => 'halmahera', 'password' => Hash::make('halmahera'), 'kode' => 'P05', 'role' => 'puskesmas', 'faskes' => 'Pusk Halmahera'],
            ['name' => 'Pusk Bugangan', 'username' => 'bugangan', 'password' => Hash::make('bugangan'), 'kode' => 'P06', 'role' => 'puskesmas', 'faskes' => 'Pusk Bugangan'],
            ['name' => 'Pusk Karangdoro', 'username' => 'karangdoro', 'password' => Hash::make('karangdoro'), 'kode' => 'P07', 'role' => 'puskesmas', 'faskes' => 'Pusk Karangdoro'],
            ['name' => 'Pusk Pandanaran', 'username' => 'pandanaran', 'password' => Hash::make('pandanaran'), 'kode' => 'P08', 'role' => 'puskesmas', 'faskes' => 'Pusk Pandanaran'],
            ['name' => 'Pusk Lamper Tengah', 'username' => 'lampertengah', 'password' => Hash::make('lampertengah'), 'kode' => 'P09', 'role' => 'puskesmas', 'faskes' => 'Pusk Lamper Tengah'],
            ['name' => 'Pusk Karangayu', 'username' => 'karangayu', 'password' => Hash::make('karangayu'), 'kode' => 'P10', 'role' => 'puskesmas', 'faskes' => 'Pusk Karangayu'],
            ['name' => 'Pusk Lebdosari', 'username' => 'lebdosari', 'password' => Hash::make('lebdosari'), 'kode' => 'P11', 'role' => 'puskesmas', 'faskes' => 'Pusk Lebdosari'],
            ['name' => 'Pusk Manyaran', 'username' => 'manyaran', 'password' => Hash::make('manyaran'), 'kode' => 'P12', 'role' => 'puskesmas', 'faskes' => 'Pusk Manyaran'],
            ['name' => 'Pusk Krobokan', 'username' => 'krobokan', 'password' => Hash::make('krobokan'), 'kode' => 'P13', 'role' => 'puskesmas', 'faskes' => 'Pusk Krobokan'],
            ['name' => 'Pusk Ngemplak Simongan', 'username' => 'ngemplaksimongan', 'password' => Hash::make('ngemplaksimongan'), 'kode' => 'P14', 'role' => 'puskesmas', 'faskes' => 'Pusk Ngemplak Simongan'],
            ['name' => 'Pusk Gayamsari', 'username' => 'gayamsari', 'password' => Hash::make('gayamsari'), 'kode' => 'P15', 'role' => 'puskesmas', 'faskes' => 'Pusk Gayamsari'],
            ['name' => 'Pusk Candilama', 'username' => 'candilama', 'password' => Hash::make('candilama'), 'kode' => 'P16', 'role' => 'puskesmas', 'faskes' => 'Pusk Candilama'],
            ['name' => 'Pusk Kagok', 'username' => 'kagok', 'password' => Hash::make('kagok'), 'kode' => 'P17', 'role' => 'puskesmas', 'faskes' => 'Pusk Kagok'],
            ['name' => 'Pusk Pegandan', 'username' => 'pegandan', 'password' => Hash::make('pegandan'), 'kode' => 'P18', 'role' => 'puskesmas', 'faskes' => 'Pusk Pegandan'],
            ['name' => 'Pusk Genuk', 'username' => 'genuk', 'password' => Hash::make('genuk'), 'kode' => 'P19', 'role' => 'puskesmas', 'faskes' => 'Pusk Genuk'],
            ['name' => 'Pusk Bangetayu', 'username' => 'bangetayu', 'password' => Hash::make('bangetayu'), 'kode' => 'P20', 'role' => 'puskesmas', 'faskes' => 'Pusk Bangetayu'],
            ['name' => 'Pusk Tlogosari Kulon', 'username' => 'tlogosarikulon', 'password' => Hash::make('tlogosarikulon'), 'kode' => 'P21', 'role' => 'puskesmas', 'faskes' => 'Pusk Tlogosari Kulon'],
            ['name' => 'Pusk Tlogosari Wetan', 'username' => 'tlogosariwetan', 'password' => Hash::make('tlogosariwetan'), 'kode' => 'P22', 'role' => 'puskesmas', 'faskes' => 'Pusk Tlogosari Wetan'],
            ['name' => 'Pusk Kedung Mundu', 'username' => 'kedungmundu', 'password' => Hash::make('kedungmundu'), 'kode' => 'P23', 'role' => 'puskesmas', 'faskes' => 'Pusk Kedung Mundu'],
            ['name' => 'Pusk Rowosari', 'username' => 'rowosari', 'password' => Hash::make('rowosari'), 'kode' => 'P24', 'role' => 'puskesmas', 'faskes' => 'Pusk Rowosari'],
            ['name' => 'Pusk Ngesrep', 'username' => 'ngesrep', 'password' => Hash::make('ngesrep'), 'kode' => 'P25', 'role' => 'puskesmas', 'faskes' => 'Pusk Ngesrep'],
            ['name' => 'Pusk Padangsari', 'username' => 'padangsari', 'password' => Hash::make('padangsari'), 'kode' => 'P26', 'role' => 'puskesmas', 'faskes' => 'Pusk Padangsari'],
            ['name' => 'Pusk Srondol', 'username' => 'srondol', 'password' => Hash::make('srondol'), 'kode' => 'P27', 'role' => 'puskesmas', 'faskes' => 'Pusk Srondol'],
            ['name' => 'Pusk Pudak Payung', 'username' => 'pudakpayung', 'password' => Hash::make('pudakpayung'), 'kode' => 'P28', 'role' => 'puskesmas', 'faskes' => 'Pusk Pudak Payung'],
            ['name' => 'Pusk Gunung Pati', 'username' => 'gunungpati', 'password' => Hash::make('gunungpati'), 'kode' => 'P29', 'role' => 'puskesmas', 'faskes' => 'Pusk Gunung Pati'],
            ['name' => 'Pusk Sekaran', 'username' => 'sekaran', 'password' => Hash::make('sekaran'), 'kode' => 'P30', 'role' => 'puskesmas', 'faskes' => 'Pusk Sekaran'],
            ['name' => 'Pusk Mijen', 'username' => 'mijen', 'password' => Hash::make('mijen'), 'kode' => 'P31', 'role' => 'puskesmas', 'faskes' => 'Pusk Mijen'],
            ['name' => 'Pusk Karangmalang', 'username' => 'karangmalang', 'password' => Hash::make('karangmalang'), 'kode' => 'P32', 'role' => 'puskesmas', 'faskes' => 'Pusk Karangmalang'],
            ['name' => 'Pusk Tambakaji', 'username' => 'tambakaji', 'password' => Hash::make('tambakaji'), 'kode' => 'P33', 'role' => 'puskesmas', 'faskes' => 'Pusk Tambakaji'],
            ['name' => 'Pusk Purwoyoso', 'username' => 'purwoyoso', 'password' => Hash::make('purwoyoso'), 'kode' => 'P34', 'role' => 'puskesmas', 'faskes' => 'Pusk Purwoyoso'],
            ['name' => 'Pusk Ngalian', 'username' => 'ngalian', 'password' => Hash::make('ngalian'), 'kode' => 'P35', 'role' => 'puskesmas', 'faskes' => 'Pusk Ngalian'],
            ['name' => 'Pusk Mangkang', 'username' => 'mangkang', 'password' => Hash::make('mangkang'), 'kode' => 'P36', 'role' => 'puskesmas', 'faskes' => 'Pusk Mangkang'],
            ['name' => 'Pusk Karanganyar', 'username' => 'karanganyar', 'password' => Hash::make('karanganyar'), 'kode' => 'P37', 'role' => 'puskesmas', 'faskes' => 'Pusk Karanganyar'],
            ['name' => 'Kader Pandansari', 'username' => 'kaderpandansari', 'password' => Hash::make('kaderpandansari'), 'kode' => 'KD01', 'role' => 'kader', 'faskes' => 'Kader Pandansari'],
            ['name' => 'Kader Bangunharjo', 'username' => 'kaderbangunharjo', 'password' => Hash::make('kaderbangunharjo'), 'kode' => 'KD02', 'role' => 'kader', 'faskes' => 'Kader Bangunharjo'],
            ['name' => 'Kader Kauman', 'username' => 'kaderkauman', 'password' => Hash::make('kaderkauman'), 'kode' => 'KD03', 'role' => 'kader', 'faskes' => 'Kader Kauman'],
            ['name' => 'Kader Purwodinatan', 'username' => 'kaderpurwodinatan', 'password' => Hash::make('kaderpurwodinatan'), 'kode' => 'KD04', 'role' => 'kader', 'faskes' => 'Kader Purwodinatan'],
            ['name' => 'Kader Pindrikan Lor', 'username' => 'kaderpindrikanlor', 'password' => Hash::make('kaderpindrikanlor'), 'kode' => 'KD05', 'role' => 'kader', 'faskes' => 'Kader Pindrikan Lor'],
            ['name' => 'Kader Kranggan', 'username' => 'kaderkranggan', 'password' => Hash::make('kaderkranggan'), 'kode' => 'KD06', 'role' => 'kader', 'faskes' => 'Kader Kranggan'],
            ['name' => 'Kader Kembangsari', 'username' => 'kaderkembangsari', 'password' => Hash::make('kaderkembangsari'), 'kode' => 'KD07', 'role' => 'kader', 'faskes' => 'Kader Kembangsari'],
            ['name' => 'Kader Pindrikan Kidul', 'username' => 'kaderpindrikankidul', 'password' => Hash::make('kaderpindrikankidul'), 'kode' => 'KD08', 'role' => 'kader', 'faskes' => 'Kader Pindrikan Kidul'],
            ['name' => 'Kader Sekayu', 'username' => 'kadersekayu', 'password' => Hash::make('kadersekayu'), 'kode' => 'KD09', 'role' => 'kader', 'faskes' => 'Kader Sekayu'],
            ['name' => 'Kader Miroto', 'username' => 'kadermiroto', 'password' => Hash::make('kadermiroto'), 'kode' => 'KD10', 'role' => 'kader', 'faskes' => 'Kader Miroto'],
            ['name' => 'Kader Tlogosari Wetan', 'username' => 'kadertlogosariwetan', 'password' => Hash::make('kadertlogosariwetan'), 'kode' => 'KD100', 'role' => 'kader', 'faskes' => 'Kader Tlogosari Wetan'],
            ['name' => 'Kader Tlogomulyo', 'username' => 'kadertlogomulyo', 'password' => Hash::make('kadertlogomulyo'), 'kode' => 'KD101', 'role' => 'kader', 'faskes' => 'Kader Tlogomulyo'],
            ['name' => 'Kader Palebon', 'username' => 'kaderpalebon', 'password' => Hash::make('kaderpalebon'), 'kode' => 'KD102', 'role' => 'kader', 'faskes' => 'Kader Palebon'],
            ['name' => 'Kader Pedurungan Tengah', 'username' => 'kaderpedurungantengah', 'password' => Hash::make('kaderpedurungantengah'), 'kode' => 'KD103', 'role' => 'kader', 'faskes' => 'Kader Pedurungan Tengah'],
            ['name' => 'Kader Pedurungan Lor', 'username' => 'kaderpedurunganlor', 'password' => Hash::make('kaderpedurunganlor'), 'kode' => 'KD104', 'role' => 'kader', 'faskes' => 'Kader Pedurungan Lor'],
            ['name' => 'Kader Plamongansari', 'username' => 'kaderplamongansari', 'password' => Hash::make('kaderplamongansari'), 'kode' => 'KD105', 'role' => 'kader', 'faskes' => 'Kader Plamongansari'],
            ['name' => 'Kader Pedurungan Kidul', 'username' => 'kaderpedurungankidul', 'password' => Hash::make('kaderpedurungankidul'), 'kode' => 'KD106', 'role' => 'kader', 'faskes' => 'Kader Pedurungan Kidul'],
            ['name' => 'Kader Penggaron Kidul', 'username' => 'kaderpenggaronkidul', 'password' => Hash::make('kaderpenggaronkidul'), 'kode' => 'KD107', 'role' => 'kader', 'faskes' => 'Kader Penggaron Kidul'],
            ['name' => 'Kader Kedungmundu', 'username' => 'kaderkedungmundu', 'password' => Hash::make('kaderkedungmundu'), 'kode' => 'KD108', 'role' => 'kader', 'faskes' => 'Kader Kedungmundu'],
            ['name' => 'Kader Tandang', 'username' => 'kadertandang', 'password' => Hash::make('kadertandang'), 'kode' => 'KD109', 'role' => 'kader', 'faskes' => 'Kader Tandang'],
            ['name' => 'Kader Brumbungan', 'username' => 'kaderbrumbungan', 'password' => Hash::make('kaderbrumbungan'), 'kode' => 'KD11', 'role' => 'kader', 'faskes' => 'Kader Brumbungan'],
            ['name' => 'Kader Jangli', 'username' => 'kaderjangli', 'password' => Hash::make('kaderjangli'), 'kode' => 'KD110', 'role' => 'kader', 'faskes' => 'Kader Jangli'],
            ['name' => 'Kader Sendangguwo', 'username' => 'kadersendangguwo', 'password' => Hash::make('kadersendangguwo'), 'kode' => 'KD111', 'role' => 'kader', 'faskes' => 'Kader Sendangguwo'],
            ['name' => 'Kader Sendangmulyo', 'username' => 'kadersendangmulyo', 'password' => Hash::make('kadersendangmulyo'), 'kode' => 'KD112', 'role' => 'kader', 'faskes' => 'Kader Sendangmulyo'],
            ['name' => 'Kader Sambiroto', 'username' => 'kadersambiroto', 'password' => Hash::make('kadersambiroto'), 'kode' => 'KD113', 'role' => 'kader', 'faskes' => 'Kader Sambiroto'],
            ['name' => 'Kader Mangunharjo tembalang', 'username' => 'kadermangunharjotembalang', 'password' => Hash::make('kadermangunharjotembalang'), 'kode' => 'KD114', 'role' => 'kader', 'faskes' => 'Kader Mangunharjo tembalang'],
            ['name' => 'Kader Rowosari', 'username' => 'kaderrowosari', 'password' => Hash::make('kaderrowosari'), 'kode' => 'KD115', 'role' => 'kader', 'faskes' => 'Kader Rowosari'],
            ['name' => 'Kader Meteseh', 'username' => 'kadermeteseh', 'password' => Hash::make('kadermeteseh'), 'kode' => 'KD116', 'role' => 'kader', 'faskes' => 'Kader Meteseh'],
            ['name' => 'Kader Kramas', 'username' => 'kaderkramas', 'password' => Hash::make('kaderkramas'), 'kode' => 'KD117', 'role' => 'kader', 'faskes' => 'Kader Kramas'],
            ['name' => 'Kader Tembalang', 'username' => 'kadertembalang', 'password' => Hash::make('kadertembalang'), 'kode' => 'KD118', 'role' => 'kader', 'faskes' => 'Kader Tembalang'],
            ['name' => 'Kader Bulusan', 'username' => 'kaderbulusan', 'password' => Hash::make('kaderbulusan'), 'kode' => 'KD119', 'role' => 'kader', 'faskes' => 'Kader Bulusan'],
            ['name' => 'Kader Jagalan', 'username' => 'kaderjagalan', 'password' => Hash::make('kaderjagalan'), 'kode' => 'KD12', 'role' => 'kader', 'faskes' => 'Kader Jagalan'],
            ['name' => 'Kader Ngesrep', 'username' => 'kaderngesrep', 'password' => Hash::make('kaderngesrep'), 'kode' => 'KD120', 'role' => 'kader', 'faskes' => 'Kader Ngesrep'],
            ['name' => 'Kader Sumurboto', 'username' => 'kadersumurboto', 'password' => Hash::make('kadersumurboto'), 'kode' => 'KD121', 'role' => 'kader', 'faskes' => 'Kader Sumurboto'],
            ['name' => 'Kader Tinjomoyo', 'username' => 'kadertinjomoyo', 'password' => Hash::make('kadertinjomoyo'), 'kode' => 'KD122', 'role' => 'kader', 'faskes' => 'Kader Tinjomoyo'],
            ['name' => 'Kader Padangsari', 'username' => 'kaderpadangsari', 'password' => Hash::make('kaderpadangsari'), 'kode' => 'KD123', 'role' => 'kader', 'faskes' => 'Kader Padangsari'],
            ['name' => 'Kader Pedalangan', 'username' => 'kaderpedalangan', 'password' => Hash::make('kaderpedalangan'), 'kode' => 'KD124', 'role' => 'kader', 'faskes' => 'Kader Pedalangan'],
            ['name' => 'Kader Jabungan', 'username' => 'kaderjabungan', 'password' => Hash::make('kaderjabungan'), 'kode' => 'KD125', 'role' => 'kader', 'faskes' => 'Kader Jabungan'],
            ['name' => 'Kader Srondol Kulon', 'username' => 'kadersrondolkulon', 'password' => Hash::make('kadersrondolkulon'), 'kode' => 'KD126', 'role' => 'kader', 'faskes' => 'Kader Srondol Kulon'],
            ['name' => 'Kader Srondol Wetan', 'username' => 'kadersrondolwetan', 'password' => Hash::make('kadersrondolwetan'), 'kode' => 'KD127', 'role' => 'kader', 'faskes' => 'Kader Srondol Wetan'],
            ['name' => 'Kader Banyumanik', 'username' => 'kaderbanyumanik', 'password' => Hash::make('kaderbanyumanik'), 'kode' => 'KD128', 'role' => 'kader', 'faskes' => 'Kader Banyumanik'],
            ['name' => 'Kader Pudakpayung', 'username' => 'kaderpudakpayung', 'password' => Hash::make('kaderpudakpayung'), 'kode' => 'KD129', 'role' => 'kader', 'faskes' => 'Kader Pudakpayung'],
            ['name' => 'Kader Gabahan', 'username' => 'kadergabahan', 'password' => Hash::make('kadergabahan'), 'kode' => 'KD13', 'role' => 'kader', 'faskes' => 'Kader Gabahan'],
            ['name' => 'Kader Gedawang', 'username' => 'kadergedawang', 'password' => Hash::make('kadergedawang'), 'kode' => 'KD130', 'role' => 'kader', 'faskes' => 'Kader Gedawang'],
            ['name' => 'Kader Gunungpati', 'username' => 'kadergunungpati', 'password' => Hash::make('kadergunungpati'), 'kode' => 'KD131', 'role' => 'kader', 'faskes' => 'Kader Gunungpati'],
            ['name' => 'Kader Plalangan', 'username' => 'kaderplalangan', 'password' => Hash::make('kaderplalangan'), 'kode' => 'KD132', 'role' => 'kader', 'faskes' => 'Kader Plalangan'],
            ['name' => 'Kader Pakintelan', 'username' => 'kaderpakintelan', 'password' => Hash::make('kaderpakintelan'), 'kode' => 'KD133', 'role' => 'kader', 'faskes' => 'Kader Pakintelan'],
            ['name' => 'Kader Nongkosawit', 'username' => 'kadernongkosawit', 'password' => Hash::make('kadernongkosawit'), 'kode' => 'KD134', 'role' => 'kader', 'faskes' => 'Kader Nongkosawit'],
            ['name' => 'Kader Cepoko', 'username' => 'kadercepoko', 'password' => Hash::make('kadercepoko'), 'kode' => 'KD135', 'role' => 'kader', 'faskes' => 'Kader Cepoko'],
            ['name' => 'Kader Jatirejo', 'username' => 'kaderjatirejo', 'password' => Hash::make('kaderjatirejo'), 'kode' => 'KD136', 'role' => 'kader', 'faskes' => 'Kader Jatirejo'],
            ['name' => 'Kader Sumurrejo', 'username' => 'kadersumurrejo', 'password' => Hash::make('kadersumurrejo'), 'kode' => 'KD137', 'role' => 'kader', 'faskes' => 'Kader Sumurrejo'],
            ['name' => 'Kader Mangunsari', 'username' => 'kadermangunsari', 'password' => Hash::make('kadermangunsari'), 'kode' => 'KD138', 'role' => 'kader', 'faskes' => 'Kader Mangunsari'],
            ['name' => 'Kader Pongangan', 'username' => 'kaderpongangan', 'password' => Hash::make('kaderpongangan'), 'kode' => 'KD139', 'role' => 'kader', 'faskes' => 'Kader Pongangan'],
            ['name' => 'Kader Karang Kidul', 'username' => 'kaderkarangkidul', 'password' => Hash::make('kaderkarangkidul'), 'kode' => 'KD14', 'role' => 'kader', 'faskes' => 'Kader Karang Kidul'],
            ['name' => 'Kader Kandri', 'username' => 'kaderkandri', 'password' => Hash::make('kaderkandri'), 'kode' => 'KD140', 'role' => 'kader', 'faskes' => 'Kader Kandri'],
            ['name' => 'Kader Sadeng', 'username' => 'kadersadeng', 'password' => Hash::make('kadersadeng'), 'kode' => 'KD141', 'role' => 'kader', 'faskes' => 'Kader Sadeng'],
            ['name' => 'Kader Sekaran', 'username' => 'kadersekaran', 'password' => Hash::make('kadersekaran'), 'kode' => 'KD142', 'role' => 'kader', 'faskes' => 'Kader Sekaran'],
            ['name' => 'Kader Sukorejo', 'username' => 'kadersukorejo', 'password' => Hash::make('kadersukorejo'), 'kode' => 'KD143', 'role' => 'kader', 'faskes' => 'Kader Sukorejo'],
            ['name' => 'Kader Kalisegoro', 'username' => 'kaderkalisegoro', 'password' => Hash::make('kaderkalisegoro'), 'kode' => 'KD144', 'role' => 'kader', 'faskes' => 'Kader Kalisegoro'],
            ['name' => 'Kader Patemon', 'username' => 'kaderpatemon', 'password' => Hash::make('kaderpatemon'), 'kode' => 'KD145', 'role' => 'kader', 'faskes' => 'Kader Patemon'],
            ['name' => 'Kader Ngijo', 'username' => 'kaderngijo', 'password' => Hash::make('kaderngijo'), 'kode' => 'KD146', 'role' => 'kader', 'faskes' => 'Kader Ngijo'],
            ['name' => 'Kader Mijen', 'username' => 'kadermijen', 'password' => Hash::make('kadermijen'), 'kode' => 'KD147', 'role' => 'kader', 'faskes' => 'Kader Mijen'],
            ['name' => 'Kader Ngadirgo', 'username' => 'kaderngadirgo', 'password' => Hash::make('kaderngadirgo'), 'kode' => 'KD148', 'role' => 'kader', 'faskes' => 'Kader Ngadirgo'],
            ['name' => 'Kader Kedungpane', 'username' => 'kaderkedungpane', 'password' => Hash::make('kaderkedungpane'), 'kode' => 'KD149', 'role' => 'kader', 'faskes' => 'Kader Kedungpane'],
            ['name' => 'Kader Pekunden', 'username' => 'kaderpekunden', 'password' => Hash::make('kaderpekunden'), 'kode' => 'KD15', 'role' => 'kader', 'faskes' => 'Kader Pekunden'],
            ['name' => 'Kader Cangkiran', 'username' => 'kadercangkiran', 'password' => Hash::make('kadercangkiran'), 'kode' => 'KD150', 'role' => 'kader', 'faskes' => 'Kader Cangkiran'],
            ['name' => 'Kader Tambangan', 'username' => 'kadertambangan', 'password' => Hash::make('kadertambangan'), 'kode' => 'KD151', 'role' => 'kader', 'faskes' => 'Kader Tambangan'],
            ['name' => 'Kader Jatisari', 'username' => 'kaderjatisari', 'password' => Hash::make('kaderjatisari'), 'kode' => 'KD152', 'role' => 'kader', 'faskes' => 'Kader Jatisari'],
            ['name' => 'Kader Wonolopo', 'username' => 'kaderwonolopo', 'password' => Hash::make('kaderwonolopo'), 'kode' => 'KD153', 'role' => 'kader', 'faskes' => 'Kader Wonolopo'],
            ['name' => 'Kader Wonoplumbon', 'username' => 'kaderwonoplumbon', 'password' => Hash::make('kaderwonoplumbon'), 'kode' => 'KD154', 'role' => 'kader', 'faskes' => 'Kader Wonoplumbon'],
            ['name' => 'Kader Pesantren', 'username' => 'kaderpesantren', 'password' => Hash::make('kaderpesantren'), 'kode' => 'KD155', 'role' => 'kader', 'faskes' => 'Kader Pesantren'],
            ['name' => 'Kader Jatibarang', 'username' => 'kaderjatibarang', 'password' => Hash::make('kaderjatibarang'), 'kode' => 'KD156', 'role' => 'kader', 'faskes' => 'Kader Jatibarang'],
            ['name' => 'Kader Karangmalang', 'username' => 'kaderkarangmalang', 'password' => Hash::make('kaderkarangmalang'), 'kode' => 'KD157', 'role' => 'kader', 'faskes' => 'Kader Karangmalang'],
            ['name' => 'Kader Bubakan', 'username' => 'kaderbubakan', 'password' => Hash::make('kaderbubakan'), 'kode' => 'KD158', 'role' => 'kader', 'faskes' => 'Kader Bubakan'],
            ['name' => 'Kader Polaman', 'username' => 'kaderpolaman', 'password' => Hash::make('kaderpolaman'), 'kode' => 'KD159', 'role' => 'kader', 'faskes' => 'Kader Polaman'],
            ['name' => 'Kader Bandarharjo', 'username' => 'kaderbandarharjo', 'password' => Hash::make('kaderbandarharjo'), 'kode' => 'KD16', 'role' => 'kader', 'faskes' => 'Kader Bandarharjo'],
            ['name' => 'Kader Purwosari Mijen', 'username' => 'kaderpurwosarimijen', 'password' => Hash::make('kaderpurwosarimijen'), 'kode' => 'KD160', 'role' => 'kader', 'faskes' => 'Kader Purwosari Mijen'],
            ['name' => 'Kader Tambakaji', 'username' => 'kadertambakaji', 'password' => Hash::make('kadertambakaji'), 'kode' => 'KD161', 'role' => 'kader', 'faskes' => 'Kader Tambakaji'],
            ['name' => 'Kader Wonosari', 'username' => 'kaderwonosari', 'password' => Hash::make('kaderwonosari'), 'kode' => 'KD162', 'role' => 'kader', 'faskes' => 'Kader Wonosari'],
            ['name' => 'Kader Purwoyoso', 'username' => 'kaderpurwoyoso', 'password' => Hash::make('kaderpurwoyoso'), 'kode' => 'KD163', 'role' => 'kader', 'faskes' => 'Kader Purwoyoso'],
            ['name' => 'Kader Kalipancur', 'username' => 'kaderkalipancur', 'password' => Hash::make('kaderkalipancur'), 'kode' => 'KD164', 'role' => 'kader', 'faskes' => 'Kader Kalipancur'],
            ['name' => 'Kader Ngaliyan', 'username' => 'kaderngaliyan', 'password' => Hash::make('kaderngaliyan'), 'kode' => 'KD165', 'role' => 'kader', 'faskes' => 'Kader Ngaliyan'],
            ['name' => 'Kader Bambankerep', 'username' => 'kaderbambankerep', 'password' => Hash::make('kaderbambankerep'), 'kode' => 'KD166', 'role' => 'kader', 'faskes' => 'Kader Bambankerep'],
            ['name' => 'Kader Wates', 'username' => 'kaderwates', 'password' => Hash::make('kaderwates'), 'kode' => 'KD167', 'role' => 'kader', 'faskes' => 'Kader Wates'],
            ['name' => 'Kader Beringin', 'username' => 'kaderberingin', 'password' => Hash::make('kaderberingin'), 'kode' => 'KD168', 'role' => 'kader', 'faskes' => 'Kader Beringin'],
            ['name' => 'Kader Gondoriyo', 'username' => 'kadergondoriyo', 'password' => Hash::make('kadergondoriyo'), 'kode' => 'KD169', 'role' => 'kader', 'faskes' => 'Kader Gondoriyo'],
            ['name' => 'Kader Tanjungmas', 'username' => 'kadertanjungmas', 'password' => Hash::make('kadertanjungmas'), 'kode' => 'KD17', 'role' => 'kader', 'faskes' => 'Kader Tanjungmas'],
            ['name' => 'Kader Podorejo', 'username' => 'kaderpodorejo', 'password' => Hash::make('kaderpodorejo'), 'kode' => 'KD170', 'role' => 'kader', 'faskes' => 'Kader Podorejo'],
            ['name' => 'Kader Mangkang Kulon', 'username' => 'kadermangkangkulon', 'password' => Hash::make('kadermangkangkulon'), 'kode' => 'KD171', 'role' => 'kader', 'faskes' => 'Kader Mangkang Kulon'],
            ['name' => 'Kader Mangkang Wetan', 'username' => 'kadermangkangwetan', 'password' => Hash::make('kadermangkangwetan'), 'kode' => 'KD172', 'role' => 'kader', 'faskes' => 'Kader Mangkang Wetan'],
            ['name' => 'Kader Mangunharjo Tugu', 'username' => 'kadermangunharjotugu', 'password' => Hash::make('kadermangunharjotugu'), 'kode' => 'KD173', 'role' => 'kader', 'faskes' => 'Kader Mangunharjo Tugu'],
            ['name' => 'Kader Tugurejo', 'username' => 'kadertugurejo', 'password' => Hash::make('kadertugurejo'), 'kode' => 'KD174', 'role' => 'kader', 'faskes' => 'Kader Tugurejo'],
            ['name' => 'Kader Jrakah', 'username' => 'kaderjrakah', 'password' => Hash::make('kaderjrakah'), 'kode' => 'KD175', 'role' => 'kader', 'faskes' => 'Kader Jrakah'],
            ['name' => 'Kader Karanganyar', 'username' => 'kaderkaranganyar', 'password' => Hash::make('kaderkaranganyar'), 'kode' => 'KD176', 'role' => 'kader', 'faskes' => 'Kader Karanganyar'],
            ['name' => 'Kader Randugarut', 'username' => 'kaderrandugarut', 'password' => Hash::make('kaderrandugarut'), 'kode' => 'KD177', 'role' => 'kader', 'faskes' => 'Kader Randugarut'],
            ['name' => 'Kader Kuningan', 'username' => 'kaderkuningan', 'password' => Hash::make('kaderkuningan'), 'kode' => 'KD18', 'role' => 'kader', 'faskes' => 'Kader Kuningan'],
            ['name' => 'Kader Dadapsari', 'username' => 'kaderdadapsari', 'password' => Hash::make('kaderdadapsari'), 'kode' => 'KD19', 'role' => 'kader', 'faskes' => 'Kader Dadapsari'],
            ['name' => 'Kader Bulu Lor', 'username' => 'kaderbululor', 'password' => Hash::make('kaderbululor'), 'kode' => 'KD20', 'role' => 'kader', 'faskes' => 'Kader Bulu Lor'],
            ['name' => 'Kader Panggung Kidul', 'username' => 'kaderpanggungkidul', 'password' => Hash::make('kaderpanggungkidul'), 'kode' => 'KD21', 'role' => 'kader', 'faskes' => 'Kader Panggung Kidul'],
            ['name' => 'Kader Purwosari SemUt', 'username' => 'kaderpurwosarisemut', 'password' => Hash::make('kaderpurwosarisemut'), 'kode' => 'KD22', 'role' => 'kader', 'faskes' => 'Kader Purwosari SemUt'],
            ['name' => 'Kader Plombokan', 'username' => 'kaderplombokan', 'password' => Hash::make('kaderplombokan'), 'kode' => 'KD23', 'role' => 'kader', 'faskes' => 'Kader Plombokan'],
            ['name' => 'Kader Panggung Lor', 'username' => 'kaderpanggunglor', 'password' => Hash::make('kaderpanggunglor'), 'kode' => 'KD24', 'role' => 'kader', 'faskes' => 'Kader Panggung Lor'],
            ['name' => 'Kader Karangtempel', 'username' => 'kaderkarangtempel', 'password' => Hash::make('kaderkarangtempel'), 'kode' => 'KD25', 'role' => 'kader', 'faskes' => 'Kader Karangtempel'],
            ['name' => 'Kader Karangturi', 'username' => 'kaderkarangturi', 'password' => Hash::make('kaderkarangturi'), 'kode' => 'KD26', 'role' => 'kader', 'faskes' => 'Kader Karangturi'],
            ['name' => 'Kader Rejosari', 'username' => 'kaderrejosari', 'password' => Hash::make('kaderrejosari'), 'kode' => 'KD27', 'role' => 'kader', 'faskes' => 'Kader Rejosari'],
            ['name' => 'Kader Sarirejo', 'username' => 'kadersarirejo', 'password' => Hash::make('kadersarirejo'), 'kode' => 'KD28', 'role' => 'kader', 'faskes' => 'Kader Sarirejo'],
            ['name' => 'Kader Bugangan', 'username' => 'kaderbugangan', 'password' => Hash::make('kaderbugangan'), 'kode' => 'KD29', 'role' => 'kader', 'faskes' => 'Kader Bugangan'],
            ['name' => 'Kader Kebonagung', 'username' => 'kaderkebonagung', 'password' => Hash::make('kaderkebonagung'), 'kode' => 'KD30', 'role' => 'kader', 'faskes' => 'Kader Kebonagung'],
            ['name' => 'Kader Mlatiharjo', 'username' => 'kadermlatiharjo', 'password' => Hash::make('kadermlatiharjo'), 'kode' => 'KD31', 'role' => 'kader', 'faskes' => 'Kader Mlatiharjo'],
            ['name' => 'Kader Rejomulyo', 'username' => 'kaderrejomulyo', 'password' => Hash::make('kaderrejomulyo'), 'kode' => 'KD32', 'role' => 'kader', 'faskes' => 'Kader Rejomulyo'],
            ['name' => 'Kader Kemijen', 'username' => 'kaderkemijen', 'password' => Hash::make('kaderkemijen'), 'kode' => 'KD33', 'role' => 'kader', 'faskes' => 'Kader Kemijen'],
            ['name' => 'Kader Mlatibaru', 'username' => 'kadermlatibaru', 'password' => Hash::make('kadermlatibaru'), 'kode' => 'KD34', 'role' => 'kader', 'faskes' => 'Kader Mlatibaru'],
            ['name' => 'Kader Barusari', 'username' => 'kaderbarusari', 'password' => Hash::make('kaderbarusari'), 'kode' => 'KD35', 'role' => 'kader', 'faskes' => 'Kader Barusari'],
            ['name' => 'Kader Bulustalan', 'username' => 'kaderbulustalan', 'password' => Hash::make('kaderbulustalan'), 'kode' => 'KD36', 'role' => 'kader', 'faskes' => 'Kader Bulustalan'],
            ['name' => 'Kader Pleburan', 'username' => 'kaderpleburan', 'password' => Hash::make('kaderpleburan'), 'kode' => 'KD37', 'role' => 'kader', 'faskes' => 'Kader Pleburan'],
            ['name' => 'Kader Wonodri', 'username' => 'kaderwonodri', 'password' => Hash::make('kaderwonodri'), 'kode' => 'KD38', 'role' => 'kader', 'faskes' => 'Kader Wonodri'],
            ['name' => 'Kader Mugassari', 'username' => 'kadermugassari', 'password' => Hash::make('kadermugassari'), 'kode' => 'KD39', 'role' => 'kader', 'faskes' => 'Kader Mugassari'],
            ['name' => 'Kader Randusari', 'username' => 'kaderrandusari', 'password' => Hash::make('kaderrandusari'), 'kode' => 'KD40', 'role' => 'kader', 'faskes' => 'Kader Randusari'],
            ['name' => 'Kader Lamper Tengah', 'username' => 'kaderlampertengah', 'password' => Hash::make('kaderlampertengah'), 'kode' => 'KD41', 'role' => 'kader', 'faskes' => 'Kader Lamper Tengah'],
            ['name' => 'Kader Lamper Kidul', 'username' => 'kaderlamperkidul', 'password' => Hash::make('kaderlamperkidul'), 'kode' => 'KD42', 'role' => 'kader', 'faskes' => 'Kader Lamper Kidul'],
            ['name' => 'Kader Lamper Lor', 'username' => 'kaderlamperlor', 'password' => Hash::make('kaderlamperlor'), 'kode' => 'KD43', 'role' => 'kader', 'faskes' => 'Kader Lamper Lor'],
            ['name' => 'Kader Peterongan', 'username' => 'kaderpeterongan', 'password' => Hash::make('kaderpeterongan'), 'kode' => 'KD44', 'role' => 'kader', 'faskes' => 'Kader Peterongan'],
            ['name' => 'Kader Karangayu', 'username' => 'kaderkarangayu', 'password' => Hash::make('kaderkarangayu'), 'kode' => 'KD45', 'role' => 'kader', 'faskes' => 'Kader Karangayu'],
            ['name' => 'Kader Salamanmloyo', 'username' => 'kadersalamanmloyo', 'password' => Hash::make('kadersalamanmloyo'), 'kode' => 'KD46', 'role' => 'kader', 'faskes' => 'Kader Salamanmloyo'],
            ['name' => 'Kader Cabean', 'username' => 'kadercabean', 'password' => Hash::make('kadercabean'), 'kode' => 'KD47', 'role' => 'kader', 'faskes' => 'Kader Cabean'],
            ['name' => 'Kader Bojong Salaman', 'username' => 'kaderbojongsalaman', 'password' => Hash::make('kaderbojongsalaman'), 'kode' => 'KD48', 'role' => 'kader', 'faskes' => 'Kader Bojong Salaman'],
            ['name' => 'Kader Kalibanteng Kulon', 'username' => 'kaderkalibantengkulon', 'password' => Hash::make('kaderkalibantengkulon'), 'kode' => 'KD49', 'role' => 'kader', 'faskes' => 'Kader Kalibanteng Kulon'],
            ['name' => 'Kader Kalibanteng Kidul', 'username' => 'kaderkalibantengkidul', 'password' => Hash::make('kaderkalibantengkidul'), 'kode' => 'KD50', 'role' => 'kader', 'faskes' => 'Kader Kalibanteng Kidul'],
            ['name' => 'Kader Tambakharjo', 'username' => 'kadertambakharjo', 'password' => Hash::make('kadertambakharjo'), 'kode' => 'KD51', 'role' => 'kader', 'faskes' => 'Kader Tambakharjo'],
            ['name' => 'Kader Gisikdrono', 'username' => 'kadergisikdrono', 'password' => Hash::make('kadergisikdrono'), 'kode' => 'KD52', 'role' => 'kader', 'faskes' => 'Kader Gisikdrono'],
            ['name' => 'Kader Manyaran', 'username' => 'kadermanyaran', 'password' => Hash::make('kadermanyaran'), 'kode' => 'KD53', 'role' => 'kader', 'faskes' => 'Kader Manyaran'],
            ['name' => 'Kader Krapyak', 'username' => 'kaderkrapyak', 'password' => Hash::make('kaderkrapyak'), 'kode' => 'KD54', 'role' => 'kader', 'faskes' => 'Kader Krapyak'],
            ['name' => 'Kader Kembangarum', 'username' => 'kaderkembangarum', 'password' => Hash::make('kaderkembangarum'), 'kode' => 'KD55', 'role' => 'kader', 'faskes' => 'Kader Kembangarum'],
            ['name' => 'Kader Krobokan', 'username' => 'kaderkrobokan', 'password' => Hash::make('kaderkrobokan'), 'kode' => 'KD56', 'role' => 'kader', 'faskes' => 'Kader Krobokan'],
            ['name' => 'Kader Tawang Mas', 'username' => 'kadertawangmas', 'password' => Hash::make('kadertawangmas'), 'kode' => 'KD57', 'role' => 'kader', 'faskes' => 'Kader Tawang Mas'],
            ['name' => 'Kader Tawang Sari', 'username' => 'kadertawangsari', 'password' => Hash::make('kadertawangsari'), 'kode' => 'KD58', 'role' => 'kader', 'faskes' => 'Kader Tawang Sari'],
            ['name' => 'Kader Ngemplak Simongan', 'username' => 'kaderngemplaksimongan', 'password' => Hash::make('kaderngemplaksimongan'), 'kode' => 'KD59', 'role' => 'kader', 'faskes' => 'Kader Ngemplak Simongan'],
            ['name' => 'Kader Bongsari', 'username' => 'kaderbongsari', 'password' => Hash::make('kaderbongsari'), 'kode' => 'KD60', 'role' => 'kader', 'faskes' => 'Kader Bongsari'],
            ['name' => 'Kader Gayamsari', 'username' => 'kadergayamsari', 'password' => Hash::make('kadergayamsari'), 'kode' => 'KD61', 'role' => 'kader', 'faskes' => 'Kader Gayamsari'],
            ['name' => 'Kader Siwalan', 'username' => 'kadersiwalan', 'password' => Hash::make('kadersiwalan'), 'kode' => 'KD62', 'role' => 'kader', 'faskes' => 'Kader Siwalan'],
            ['name' => 'Kader Tambakrejo', 'username' => 'kadertambakrejo', 'password' => Hash::make('kadertambakrejo'), 'kode' => 'KD63', 'role' => 'kader', 'faskes' => 'Kader Tambakrejo'],
            ['name' => 'Kader Kaligawe', 'username' => 'kaderkaligawe', 'password' => Hash::make('kaderkaligawe'), 'kode' => 'KD64', 'role' => 'kader', 'faskes' => 'Kader Kaligawe'],
            ['name' => 'Kader Sawah Besar', 'username' => 'kadersawahbesar', 'password' => Hash::make('kadersawahbesar'), 'kode' => 'KD65', 'role' => 'kader', 'faskes' => 'Kader Sawah Besar'],
            ['name' => 'Kader Sambirejo', 'username' => 'kadersambirejo', 'password' => Hash::make('kadersambirejo'), 'kode' => 'KD66', 'role' => 'kader', 'faskes' => 'Kader Sambirejo'],
            ['name' => 'Kader Pandean Lamper', 'username' => 'kaderpandeanlamper', 'password' => Hash::make('kaderpandeanlamper'), 'kode' => 'KD67', 'role' => 'kader', 'faskes' => 'Kader Pandean Lamper'],
            ['name' => 'Kader Karanganyar Gunung', 'username' => 'kaderkaranganyargunung', 'password' => Hash::make('kaderkaranganyargunung'), 'kode' => 'KD68', 'role' => 'kader', 'faskes' => 'Kader Karanganyar Gunung'],
            ['name' => 'Kader Jomblang', 'username' => 'kaderjomblang', 'password' => Hash::make('kaderjomblang'), 'kode' => 'KD69', 'role' => 'kader', 'faskes' => 'Kader Jomblang'],
            ['name' => 'Kader Jatingaleh', 'username' => 'kaderjatingaleh', 'password' => Hash::make('kaderjatingaleh'), 'kode' => 'KD70', 'role' => 'kader', 'faskes' => 'Kader Jatingaleh'],
            ['name' => 'Kader Wonotingal', 'username' => 'kaderwonotingal', 'password' => Hash::make('kaderwonotingal'), 'kode' => 'KD71', 'role' => 'kader', 'faskes' => 'Kader Wonotingal'],
            ['name' => 'Kader Candi', 'username' => 'kadercandi', 'password' => Hash::make('kadercandi'), 'kode' => 'KD72', 'role' => 'kader', 'faskes' => 'Kader Candi'],
            ['name' => 'Kader Kaliwiru', 'username' => 'kaderkaliwiru', 'password' => Hash::make('kaderkaliwiru'), 'kode' => 'KD73', 'role' => 'kader', 'faskes' => 'Kader Kaliwiru'],
            ['name' => 'Kader Tegalsari', 'username' => 'kadertegalsari', 'password' => Hash::make('kadertegalsari'), 'kode' => 'KD74', 'role' => 'kader', 'faskes' => 'Kader Tegalsari'],
            ['name' => 'Kader Sampangan', 'username' => 'kadersampangan', 'password' => Hash::make('kadersampangan'), 'kode' => 'KD75', 'role' => 'kader', 'faskes' => 'Kader Sampangan'],
            ['name' => 'Kader Bendan Ngisor', 'username' => 'kaderbendanngisor', 'password' => Hash::make('kaderbendanngisor'), 'kode' => 'KD76', 'role' => 'kader', 'faskes' => 'Kader Bendan Ngisor'],
            ['name' => 'Kader Bendan Duwur', 'username' => 'kaderbendanduwur', 'password' => Hash::make('kaderbendanduwur'), 'kode' => 'KD77', 'role' => 'kader', 'faskes' => 'Kader Bendan Duwur'],
            ['name' => 'Kader Gajahmungkur', 'username' => 'kadergajahmungkur', 'password' => Hash::make('kadergajahmungkur'), 'kode' => 'KD78', 'role' => 'kader', 'faskes' => 'Kader Gajahmungkur'],
            ['name' => 'Kader Lempongsari', 'username' => 'kaderlempongsari', 'password' => Hash::make('kaderlempongsari'), 'kode' => 'KD79', 'role' => 'kader', 'faskes' => 'Kader Lempongsari'],
            ['name' => 'Kader Petompon', 'username' => 'kaderpetompon', 'password' => Hash::make('kaderpetompon'), 'kode' => 'KD80', 'role' => 'kader', 'faskes' => 'Kader Petompon'],
            ['name' => 'Kader Bendungan', 'username' => 'kaderbendungan', 'password' => Hash::make('kaderbendungan'), 'kode' => 'KD81', 'role' => 'kader', 'faskes' => 'Kader Bendungan'],
            ['name' => 'Kader Karangrejo', 'username' => 'kaderkarangrejo', 'password' => Hash::make('kaderkarangrejo'), 'kode' => 'KD82', 'role' => 'kader', 'faskes' => 'Kader Karangrejo'],
            ['name' => 'Kader Genuksari', 'username' => 'kadergenuksari', 'password' => Hash::make('kadergenuksari'), 'kode' => 'KD83', 'role' => 'kader', 'faskes' => 'Kader Genuksari'],
            ['name' => 'Kader Banjardowo', 'username' => 'kaderbanjardowo', 'password' => Hash::make('kaderbanjardowo'), 'kode' => 'KD84', 'role' => 'kader', 'faskes' => 'Kader Banjardowo'],
            ['name' => 'Kader Trimulyo', 'username' => 'kadertrimulyo', 'password' => Hash::make('kadertrimulyo'), 'kode' => 'KD85', 'role' => 'kader', 'faskes' => 'Kader Trimulyo'],
            ['name' => 'Kader Muktiharjo Lor', 'username' => 'kadermuktiharjolor', 'password' => Hash::make('kadermuktiharjolor'), 'kode' => 'KD86', 'role' => 'kader', 'faskes' => 'Kader Muktiharjo Lor'],
            ['name' => 'Kader Terboyo Kulon', 'username' => 'kaderterboyokulon', 'password' => Hash::make('kaderterboyokulon'), 'kode' => 'KD87', 'role' => 'kader', 'faskes' => 'Kader Terboyo Kulon'],
            ['name' => 'Kader Terboyo Wetan', 'username' => 'kaderterboyowetan', 'password' => Hash::make('kaderterboyowetan'), 'kode' => 'KD88', 'role' => 'kader', 'faskes' => 'Kader Terboyo Wetan'],
            ['name' => 'Kader Gebangsari', 'username' => 'kadergebangsari', 'password' => Hash::make('kadergebangsari'), 'kode' => 'KD89', 'role' => 'kader', 'faskes' => 'Kader Gebangsari'],
            ['name' => 'Kader Bangetayu Kulon', 'username' => 'kaderbangetayukulon', 'password' => Hash::make('kaderbangetayukulon'), 'kode' => 'KD90', 'role' => 'kader', 'faskes' => 'Kader Bangetayu Kulon'],
            ['name' => 'Kader Bangetayu Wetan', 'username' => 'kaderbangetayuwetan', 'password' => Hash::make('kaderbangetayuwetan'), 'kode' => 'KD91', 'role' => 'kader', 'faskes' => 'Kader Bangetayu Wetan'],
            ['name' => 'Kader Sembungharjo', 'username' => 'kadersembungharjo', 'password' => Hash::make('kadersembungharjo'), 'kode' => 'KD92', 'role' => 'kader', 'faskes' => 'Kader Sembungharjo'],
            ['name' => 'Kader Penggaron Lor', 'username' => 'kaderpenggaronlor', 'password' => Hash::make('kaderpenggaronlor'), 'kode' => 'KD93', 'role' => 'kader', 'faskes' => 'Kader Penggaron Lor'],
            ['name' => 'Kader Kudu', 'username' => 'kaderkudu', 'password' => Hash::make('kaderkudu'), 'kode' => 'KD94', 'role' => 'kader', 'faskes' => 'Kader Kudu'],
            ['name' => 'Kader Karangroto', 'username' => 'kaderkarangroto', 'password' => Hash::make('kaderkarangroto'), 'kode' => 'KD95', 'role' => 'kader', 'faskes' => 'Kader Karangroto'],
            ['name' => 'Kader Tlogosari Kulon', 'username' => 'kadertlogosarikulon', 'password' => Hash::make('kadertlogosarikulon'), 'kode' => 'KD96', 'role' => 'kader', 'faskes' => 'Kader Tlogosari Kulon'],
            ['name' => 'Kader Gemah', 'username' => 'kadergemah', 'password' => Hash::make('kadergemah'), 'kode' => 'KD97', 'role' => 'kader', 'faskes' => 'Kader Gemah'],
            ['name' => 'Kader Kalicari', 'username' => 'kaderkalicari', 'password' => Hash::make('kaderkalicari'), 'kode' => 'KD98', 'role' => 'kader', 'faskes' => 'Kader Kalicari'],
            ['name' => 'Kader Muktiharjo Kidul', 'username' => 'kadermuktiharjokidul', 'password' => Hash::make('kadermuktiharjokidul'), 'kode' => 'KD99', 'role' => 'kader', 'faskes' => 'Kader Muktiharjo Kidul'],
        ]);
    }
}
